version: "3.1"
services:
  ydl_api_ng:
    container_name: ydl_api_ng
    image: ydl_api_ng
    restart: unless-stopped
    depends_on:
      - ydl_api_ng_redis
    build:
      context: .
    ports:
      - 5011:80
    volumes:
      - ./params:/app/params
      - ./logs:/app/logs
      - ./downloads:/app/downloads
    environment:
      - UID=1000
      - GID=1000
      - NB_WORKERS=5
      - LOG_LEVEL=trace
    networks:
      - ydl_api_ng

  ydl_api_ng_redis:
    container_name: ydl_api_ng_redis
    image: redis
    restart: unless-stopped
    networks:
      - ydl_api_ng

networks:
  ydl_api_ng:

