name: Build docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml

  generate_docker_image:
    needs: unit_tests
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: readableTime

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ${{ github.workspace }}
        push: true
        tags: totonyus/ydl_api_ng
        build-args:
          - GIT_BRANCH=${{ GITHUB_REF }}
          - GIT_REVISION=${{ GITHUB_SHA }}
          - DATE=${{ steps.current-time.outputs.time }}

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: totonyus/ydl_api_ng
        readme-filepath: ${{ github.workspace }}/readme.md
